version: "2"
services:
  # web:
  #   build: .
  #   ports:
  #   - "8080:8080"
  #   depends_on:
  #   - mongo
  mongo:
    image: mongo
    ports:
    - "27017:27017"
    volumes:
    - data-volume:/data/db
  redis:
    image: redis:5-alpine
    container_name: redis
    ports:
    - "6379:6379"
    expose:
      - 6379
volumes:
  data-volume: